config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  get '/session-viewer' => "sessions#view_session"
  get '/sessions/select/:id' => "sessions#add_sessions"

  get '/ideas' => "ideas#index"
  get '/ideas/new' => "ideas#new"
  post '/ideas' => "ideas#create"
  resources :sessions, only: [:new, :create, :destroy]
  resources :teachers, only: [:show]
  resources :cohorts, only: [:new, :create, :show, :update] do
    resources :students, only: [:new, :create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :rounds, only: [:create, :update]
  resources :votes, only: [:create]
  resources :phases, only: [:update]
  resources :choices, only: [:create]
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :city
  has_many :students
  has_many :rounds
  has_many :votes, through: :rounds
  has_many :teachers, through: :city
  has_many :ideas, through: :students
  has_many :groups, through: :ideas, source: :group

  PHASES = ["ideas", "voting", "preference", "alteration", "finished"]

  validates :name, :city, presence: true
  validates :name, uniqueness: { scope: :city_id }

  def next_phase
    index = self.class::PHASES.index(self.current_phase)
    if index < 4
      update_attribute(:current_phase, self.class::PHASES[index + 1])
      self.rounds.create if self.current_phase == "voting"
    end
  end

  def current_round
    if self.current_phase != "voting"
      0
    else
      self.rounds.count
    end
  end

  def closed?
    self.current_phase == "finished"
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def new
    @cohort = Cohort.new
    @city = current_user.city
  end

  def create
    city = current_user.city || City.new
    @cohort = city.cohorts.create(cohort_params)

    if @cohort.valid?
      flash[:success] = "Cohort successfully created."
      redirect_to current_user
    else
      flash[:fail] = @cohort.errors.full_messages.first
      redirect_to new_cohort_path
    end
  end

  def show
    @cohort = Cohort.find_by_id(params[:id])
    @students = @cohort.students
    @phase = @cohort.current_phase
  end

  # def edit
  #   @cohort = Cohort.find_by_id(params[:id])
  # end

  def update
    @cohort = Cohort.find_by_id(params[:id])
    @cohort.votes.each { |vote| vote.destory }
    @cohort.rounds.each { |round| round.destroy }
    @cohort.update_attribute(:current_phase, "ideas")
    @cohort.students.each { |student| student.update_attribute(:current_access, "") }
    redirect_to @cohort
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name)
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/edit.html.erb
<div class="form-container">
  <%= form_for @cohort, edit_cohort_path(@cohort, action: "fill"), :html => {:id => "new-cohort-form", :class => "new-cohort-form"} do |f|%>
    <div class="form-group">
      <%= f.label "Name" %>
      <%= f.text_field :name, class:"form-control" %><br>
    </div>

    <div class="alert alert-info" role="alert">
      City: <%= current_user.city.name %>
    </div>

    <% if flash[:fail] %>
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <%= flash[:fail] %>
      </div>
    <% end %>

    <div class="btn-container" align="center">
      <%= f.submit "submit", class: "btn btn-primary btn-lg medium-btn" %>
    </div>
  <% end %>
</div>

app/views/cohorts/new.html.erb
<div class="form-container">
  <%= form_for @cohort, url: { action: "create", controller: "cohorts" }, :html => {:id => "new-cohort-form", :class => "new-cohort-form"} do |f|%>
    <h3 class="text-center headers">New Cohort</h3>
    <div class="form-group">
      <%= f.label "Name" %>
      <%= f.text_field :name, class:"form-control" %><br>
    </div>

    <div class="alert alert-info" role="alert">
      City: <%= current_user.city.name %>
    </div>

    <% if flash[:fail] %>
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <%= flash[:fail] %>
      </div>
    <% end %>

    <div class="btn-container" align="center">
      <%= f.submit "submit", class: "btn btn-primary btn-lg medium-btn" %>
    </div>
  <% end %>
</div>

app/views/cohorts/show.html.erb
<div class="make-reset-cohorts">
  <h3><span class="cohort-show-text"><%=@cohort.name.capitalize %> - <%= @cohort.city.name %></span></h3>
  <div class="phase-switch-btn">
  <% if @phase == "ideas" %>
    <% if @students.find { |student| student.current_access == "ideas" } %>
        <%= link_to "Next Phase: Voting", phase_path(cohort_id: @cohort.id), method: :patch, class: "btn btn-primary"%>
    <% else %>
      <%= link_to "Open Ideas Phase", phase_path(cohort_id: @cohort.id), method: :patch, class: "btn btn-primary" %>
    <% end %>
  <% elsif @phase == "voting" %>
    <p> </p>
    <h4><span class="cohort-show-text">Voting Round <%= @cohort.current_round %></span></h4>
    <% if @students.find { |student| student.current_access.include? "voting" } %>
      <%= link_to "End Voting Round", round_path(@cohort.rounds.find_by_voting_round(@cohort.current_round)), method: :patch, class: "btn btn-primary" %>
    <% elsif @cohort.rounds.find_by_voting_round(@cohort.current_round).votes.any? %>
      <% if @cohort.ideas.select { |idea| idea.active? }.count <= 4 %>
        <%= link_to "Next Phase: Preference Voting", phase_path(cohort_id: @cohort.id), method: :patch, class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Next Voting Round", rounds_path(cohort_id: @cohort.id), method: :post, class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= link_to "Open Voting Round", round_path(@cohort.rounds.find_by_voting_round(@cohort.current_round)), method: :patch, class: "btn btn-primary" %>
    <% end %>
  <% elsif @phase == "preference" %>
    <% if @students.find { |student| student.current_access.include? "preference" } %>
      <%= link_to "End Preference Voting", phase_path(cohort_id: @cohort.id), method: :patch, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Open Preference Voting", phase_path(cohort_id: @cohort.id), method: :patch, class: "btn btn-primary" %>
    <% end %>
  <% elsif @phase == "alteration" %>
    <%= link_to "Alter Groups", cohort_groups_path(@cohort), class: "btn btn-primary" %>
  <% elsif @phase == "finished" %>
    <%= link_to "View Groups", cohort_groups_path(@cohort), class: "btn btn-primary" %>
  <% end %>
  </div>
  <p>   </p>
  <div class="reset-cohort-btn">
    <%= link_to "Reset Cohort", cohort_path(@cohort), method: :patch, class: "btn btn-danger" %>
  </div>
</div>
<div class="student-right">
  <h4><span class="cohort-show-text">Students</span></h4>
  <% if flash[:success] %>
    <div class="alert alert-success" role="alert">
      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      <%= flash[:success] %>
    </div>
  <% end %>
  <ul>
    <% @students.each do |student| %>
      <li><span class="cohort-show-text"><%= student.full_name %> | <%= student.email %></span></li>
    <% end %>
  </ul>
  <div class="create-student-btn">
    <%= link_to "Add Student", new_cohort_student_path(@cohort), class: "btn btn-primary" %>
  </div>
</div>