config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  get '/session-viewer' => "sessions#view_session"
  get '/sessions/select/:id' => "sessions#add_sessions"

  get '/ideas' => "ideas#index"
  get '/ideas/new' => "ideas#new"
  post '/ideas' => "ideas#create"
  resources :sessions, only: [:new, :create, :destroy]
  resources :teachers, only: [:show]
  resources :cohorts, only: [:new, :create, :show, :update] do
    resources :students, only: [:new, :create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :rounds, only: [:create, :update]
  resources :votes, only: [:create]
  resources :phases, only: [:update]
  resources :choices, only: [:create]
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :student
  has_one :cohort, through: :student
  has_one :group
  has_many :votes
  has_many :choices
  has_many :rounds, through: :votes, source: :round

  validates :title, :student, :cohort, presence: true
  validate :unique_in_cohort

  def unique_in_cohort
    unless self.student
      return errors.add :student, "must exists"
    end

    cohort_idea_names = self.student.cohort.ideas.map { |idea| idea.title }
    if cohort_idea_names.include? self.title
      errors.add :title, "has already been taken"
    end
  end

  def active?
    self.active == 1
  end

  def vote_count(round)
    self.votes.select { |vote| vote.round == round }.count
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :require_login

  def index
    @student = current_user
    @ideas = @student.cohort.ideas.select {|idea| idea.active?}
  end

  def new
    @idea = Idea.new
  end

  def create
    @student = current_user
    @idea = @student.ideas.build(idea_params)
    if @idea.save
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def add_sessions
    @ideas = Idea.all
    @idea = Idea.find_by_id(params[:id])
    if session[:selection]
      if session[:selection].count >= 3
        flash[:error] = "Student can only vote 3 ideas each round."
        redirect_to ideas_path
      elsif !session[:selection].include?(@idea.id)
        session[:selection] << @idea.id
      else
        session[:selection].delete(@idea.id)
      end
    else
      session[:selection] = [@idea.id]
    end
    redirect_to ideas_path
  end

  private

  def idea_params
    params.require(:idea).permit(:title)
  end

  def require_login
    unless current_user
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_path
    end
  end
end

app/helpers/idea_helper.rb
module IdeaHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/index.html.erb
<% if current_user.is_a?(Student) && current_user.current_access == "preference" %>
  <div class="alert alert-info" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    Rearrange ideas from most preferred(top) to least preferred(bottom).
  </div>
  <div class='table-container'>
    <div class ="jform"></div>
    <table class='table table sorted_table'>
      <thead>
        <tr class="idea-header">
          <th><h3 class='headers text-center'>Choose Your Final Project</h3></th>
        </tr>
      </thead>
      <tbody>
        <% @ideas.each do |idea| %>
          <tr class='idea-tr'>
            <td class="text-center idea-listing"><span id="idea-<%= idea.id %>" class="title-listing"><%= idea.title %></span></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<% if current_user.choices.empty? %>
    <div class="submit-preference" align="center">
      <%= link_to "Submit", choices_path, method: :create,  class: "btn btn-primary btn-lg medium-btn prf-btn" %>
    </div>
<% end %>
<% else %>
  <% if current_user.is_a? Student %>
      <div class="create-idea-btn" align="center">
        <% if current_user.current_access == "ideas" %>
          <%= link_to "Create Idea", ideas_new_path,  class: "btn btn-primary btn-lg medium-btn" %>
        <% end %>
      </div>

      <% if can_vote? %>
        <div align="center" class="remain-sign" align="center">
          <div class="alert alert-info remain-box" role="alert">
            <span id="remaining-vote">
              Remaining Votes:
                <% if session[:selection] %>
                  <span id="num-remaining"><%= 3 - session[:selection].count %></span>
                <% else %>
                  <span id="num-remaining">3</span>
                <% end %>
            </span>
          </div>
        </div>

        <div id="remaining-vote-error">
          <% if flash[:error] %>
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">Error:</span>
              <%= flash[:error] %>
            </div>
          <% end %>
        </div>
      <% end %>
  <% end %>

  <div class='table-container'>
    <div class ="jform"></div>
    <table class='table table'>
      <tr class="idea-header">
        <th colspan="3"><h3 class='headers text-center'>DBC Final Project Ideas</h3></th>
      </tr>
      <% @ideas.each do |idea| %>

        <tr class='idea-tr'>

          <td align="center" class="bulb-col">
            <% if voted_idea_this_round?(idea) || ((session[:selection] != nil) && (session[:selection].include? idea.id)) %>
              <i class="fa fa-lightbulb-o fa-3x bulb-btn yellow-bulb" aria-hidden="true"></i>
            <% else %>
              <i class="fa fa-lightbulb-o fa-3x bulb-btn" aria-hidden="true"></i>
            <% end %>
          </td>

          <td class="text-center idea-listing"><span class="title-listing"><%= idea.title %><span></td>

            <% if voted_idea_this_round?(idea) || ((session[:selection] != nil) && (session[:selection].include? idea.id)) %>
              <td align="center" class="vote-col"><% if can_vote? %><a id="<%= idea.id %>" href="/sessions/select/<%= idea.id %>" class= "btn btn-success btn-lg vote-btn">Vote</a><% end %></td>
            <% else %>
              <td align="center" class="vote-col"><% if can_vote? %><a id="<%= idea.id %>" href="/sessions/select/<%= idea.id %>" class= "btn btn-default btn-lg vote-btn">Vote</a><% end %></td>
            <% end %>
        </tr>

      <% end %>
    </table>
  </div>

  <% if current_user.is_a? Student %>
    <div class="create-idea-btn" align="center">
      <% if can_vote? %>
        <%= link_to "Submit", votes_path, method: :post, class: "btn btn-primary btn-lg medium-btn" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/ideas/new.html.erb
<div class="form-container">

  <%= form_for(@idea) do |f| %>
    <h3 class="text-center headers">New Idea</h3>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>
    </div>

<!--     <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      Integration with login/logout feature required!!
    </div> -->

    <div class="btn-container" align="center">
      <%= f.submit class: "btn btn-primary btn-lg login-btn"%>
    </div>
  <% end %>

</div>