config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  get '/session-viewer' => "sessions#view_session"
  get '/sessions/select/:id' => "sessions#add_sessions"

  get '/ideas' => "ideas#index"
  get '/ideas/new' => "ideas#new"
  post '/ideas' => "ideas#create"
  resources :sessions, only: [:new, :create, :destroy]
  resources :teachers, only: [:show]
  resources :cohorts, only: [:new, :create, :show, :update] do
    resources :students, only: [:new, :create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :rounds, only: [:create, :update]
  resources :votes, only: [:create]
  resources :phases, only: [:update]
  resources :choices, only: [:create]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students
  belongs_to :idea
  has_one :cohort, through: :idea

  validates :name, presence: true
  validates :idea, presence: true, uniqueness: true

  before_validation :generate_name, on: :create

  def generate_name
    unless self.name
      self.name = "group #{self.cohort.groups.count + 1}" if self.cohort
    end
  end

  # if the group is filled
  def filled?(limit)
    self.students.count == limit
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @cohort = Cohort.find_by_id(params[:cohort_id])
    @groups = @cohort.groups
  end

  # def create
  #   p request
  #   redirect_to groups_path
  # end

  def update
    puts "==================="
    keys = params[:groupObj].keys
    keys.each do |group_id|
      group = Group.find_by_id(group_id.to_i)
      students = params[:groupObj][group_id]
      students.each do |student_id|
        student = Student.find_by_id(student_id.to_i)
        student.group = group
        student.save
      end
    end
    @cohort = Cohort.find_by_id(params[:cohort_id])
    @cohort.next_phase
    if request.xhr?
      "done"
    else
      redirect_to cohort_groups_path(@cohort)
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<% if @cohort.current_phase == "finished" %>
<div class="groups">
  <div class="row">
      <% @groups.each do |group| %>
      <div class="col-md-4 group-lists" align="center">
        <div class="group-label">
          <%= group.name %> - <%= group.idea.title %>
        </div>
        <ul align="center" id="group-<%=group.id%>" class="list-group">
          <% group.students.each do |student| %>
            <li class="list-group-item" id="student-<%=student.id%>"><%=student.full_name%></li>
          <% end %>
        </ul>
      </div>
      <% end %>
  </div>
</div>
<% else %>
  <div class="alert alert-info hidden" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    All Groups Finalized.
  </div>
  <p id="cohort_id" class="hidden"><%= @cohort.id %></p>
  <div class="groups">
    <div class="row">
        <% @groups.each do |group| %>
        <div class="col-md-4 group-lists" align="center">
          <div class="group-label">
            <%= group.name %> - <%= group.idea.title %>
          </div>
          <ul align="center" id="group-<%=group.id%>" class="simple_with_drop list-group">
            <% group.students.each do |student| %>
              <li class="list-group-item" id="student-<%=student.id%>"><%=student.full_name%></li>
            <% end %>
          </ul>
        </div>
        <% end %>
    </div>
  </div>
  <div class="submit-group" align="center">
    <%= link_to "Save Group", cohort_group_path(@cohort, 0), method: :put,  class: "btn btn-primary btn-lg medium-btn grp-btn" %>
  </div>
<% end %>