config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  get '/session-viewer' => "sessions#view_session"
  get '/sessions/select/:id' => "sessions#add_sessions"

  get '/ideas' => "ideas#index"
  get '/ideas/new' => "ideas#new"
  post '/ideas' => "ideas#create"
  resources :sessions, only: [:new, :create, :destroy]
  resources :teachers, only: [:show]
  resources :cohorts, only: [:new, :create, :show, :update] do
    resources :students, only: [:new, :create]
    resources :groups, only: [:index, :create, :update]
  end
  resources :rounds, only: [:create, :update]
  resources :votes, only: [:create]
  resources :phases, only: [:update]
  resources :choices, only: [:create]
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :city
  has_many :cohorts, through: :city
  has_many :students, through: :cohorts

  validates :first_name, :last_name, :email, :access_code, :city, presence: true
  validates :access_code, :email, uniqueness: true

  before_validation :generate_access_code, on: :create

  def generate_access_code
    if !self.access_code && self.first_name && self.last_name
      self.access_code = (self.first_name + self.last_name[0]).downcase
    end
  end

  def authenticate(password)
    self if self.access_code == password
  end

  # -- Display ----------------------------------------

  def full_name
    self.first_name.capitalize + " " + self.last_name.capitalize
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def show
    @cohorts = current_user.cohorts.sort_by { |cohort| cohort.created_at }.reverse
  end
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/teachers/show.html.erb
<div>
  <h2><span class="cohort-show-text">Cohorts</span></h2>
  <div>
    <div class="create-cohort-btn">
      <%= link_to "New Cohort", new_cohort_path, class: "btn btn-primary btn-lg text-left" %>
      <p>  </p>
    </div>

    <ul class="teacher-cohort-lists">
      <% @cohorts.each do |cohort| %>
        <li>
          <%= link_to cohort.name.capitalize, cohort, class: "btn btn-info btn-lg text-left" %>
          <span class="mark"><%= "Active Status" unless cohort.closed? %></span>
          <p> </p>
        </li>
      <% end %>
    </ul>
  </div>
</div>